title: Mickael Barbieri 
logo: /assets/img/Photo-Photoroom.png
description: Data Analyst interested in social media, social listening, web analysis and platforms. Experienced journalist with digital communication and marketing background.
show_downloads: true
theme: jekyll-theme-minimal

